name: CI

on:
  pull_request:

jobs:
  ci:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - v1.1/software/esphome/powerflie-noaddon-factory.yaml
          - v1.1/software/esphome/powerflie-1addon-factory.yaml
          - v1.1/software/esphome/powerflie-2addons-factory.yaml

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@1.8.0
        with:
          yaml_file: ${{ matrix.file }}
          version: latest
          platform: amd64
