name: Build and Publish PowerFlies firmware and website

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'v1.1/software/esphome/**'

permissions:
  contents: write

jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: v1.1/software/esphome/powerflie-noaddon-factory.yaml, v1.1/software/esphome/powerflie-1addon-factory.yaml, v1.1/software/esphome/powerflie-2addons-factory.yaml
      name: Enerwize-powerflies-esphome
